-- System Design Problems - 50 Problems

USE faang;

-- System Design Problem 1
INSERT INTO problem (module_type, category, arena, title, description_markdown, hints_markdown, solution_explanation_markdown, difficulty, tags)
VALUES (
    'SYS_DESIGN',
    'META',
    'SYSTEM_DESIGN',
    'Horizontal Database Scaling',
    '# Horizontal Database Scaling\n\nA single database is becoming a bottleneck. What strategies can you use to scale writes horizontally?\n\n**Scenario:**\n- Current: Single MySQL instance\n- Problem: Write throughput maxed out\n- Requirements: Maintain consistency where possible',
    'Hint 1: Consider sharding strategies (range, hash, geographic).\n---\nHint 2: Read replicas help with reads, not writes.\n---\nHint 3: Think about partition keys and hot spots.',
    '## Solution Strategies:\n\n**1. Sharding (Horizontal Partitioning)**\n- Split data across multiple database servers\n- Partition key selection is critical (user_id, geography, etc.)\n- Avoid hot shards with good hash functions\n\n**2. CQRS (Command Query Responsibility Segregation)**\n- Separate write and read models\n- Write to optimized write stores\n- Replicate to read-optimized stores\n\n**3. Write-Optimized Databases**\n- Use Cassandra or DynamoDB for high write throughput\n- NoSQL databases often scale writes better\n\n**Trade-offs:**\n- Cross-shard queries become complex\n- Distributed transactions are hard\n- Need application-level routing logic',
    'HARD',
    'system-design,database,scaling,sharding'
);

-- System Design Problem 2
INSERT INTO problem (module_type, category, arena, title, description_markdown, hints_markdown, solution_explanation_markdown, difficulty, tags)
VALUES (
    'SYS_DESIGN',
    'GOOGLE',
    'SYSTEM_DESIGN',
    'Monolith to Microservices Migration',
    '# Monolith to Microservices Migration\n\nWhat changes are needed to migrate a monolithic service to a microservices architecture safely?\n\n**Current State:**\n- Large monolithic application\n- Shared database\n- Tight coupling between modules',
    'Hint 1: Start with the Strangler Fig pattern.\n---\nHint 2: Identify bounded contexts and service boundaries.\n---\nHint 3: Database per service, but migrate gradually.',
    '## Migration Strategy:\n\n**1. Strangler Fig Pattern**\n- Gradually extract services from monolith\n- Route new features to new services\n- Proxy old requests through facade\n\n**2. Service Identification**\n- Domain-Driven Design (DDD)\n- Identify bounded contexts\n- Look for low coupling, high cohesion\n\n**3. Database Decomposition**\n- Start with database views\n- Move to separate schemas\n- Eventually separate database instances\n- Use event sourcing for cross-service data\n\n**4. API Gateway**\n- Single entry point\n- Handle authentication, routing\n- Rate limiting, caching\n\n**5. Observability**\n- Distributed tracing (Jaeger, Zipkin)\n- Centralized logging\n- Service mesh for traffic management\n\n**Challenges:**\n- Distributed transactions\n- Network latency\n- Debugging complexity\n- Data consistency',
    'HARD',
    'system-design,microservices,architecture,migration'
);

-- System Design Problem 3
INSERT INTO problem (module_type, category, arena, title, description_markdown, hints_markdown, solution_explanation_markdown, difficulty, tags)
VALUES (
    'SYS_DESIGN',
    'AMAZON',
    'SYSTEM_DESIGN',
    'Global Data Replication with Strong Consistency',
    '# Global Data Replication\n\nHow can you replicate data globally without violating consistency guarantees required by financial transactions?\n\n**Requirements:**\n- Multi-region deployment\n- Strong consistency for financial data\n- Low latency for reads\n- ACID transactions',
    'Hint 1: CAP theorem - can''t have both low latency AND strong consistency globally.\n---\nHint 2: Consider consensus protocols like Raft or Paxos.\n---\nHint 3: Hybrid approach: strong consistency in primary region, eventual elsewhere.',
    '## Solutions:\n\n**1. Primary Region with Synchronous Replication**\n- Write to primary region with quorum\n- Synchronous replication to replicas in same region\n- Asynchronous to other regions (eventual consistency)\n- Reads go to nearest region (may be stale)\n\n**2. CockroachDB / Spanner Approach**\n- Use distributed consensus (Raft)\n- Transactions span multiple regions\n- TrueTime API for global ordering (Google Spanner)\n- Higher latency but strong consistency\n\n**3. CRDT (Conflict-Free Replicated Data Types)**\n- For specific data structures\n- Eventual consistency with guaranteed convergence\n- Works for counters, sets, registers\n\n**4. Split by Data Type**\n- Financial transactions: Strong consistency, single region\n- User profiles: Eventual consistency, multi-region\n- Different consistency models for different data\n\n**Trade-offs:**\n- Strong consistency = higher latency\n- Cross-region transactions are expensive\n- Network partitions will block writes',
    'HARD',
    'system-design,replication,consistency,cap-theorem'
);

-- System Design Problem 4
INSERT INTO problem (module_type, category, arena, title, description_markdown, hints_markdown, solution_explanation_markdown, difficulty, tags)
VALUES (
    'SYS_DESIGN',
    'META',
    'SYSTEM_DESIGN',
    'Handling Network Partitions',
    '# Network Partitions (CAP Theorem)\n\nHow do you ensure your system works correctly when network partitions occur between two regions?\n\n**Scenario:**\n- Multi-region deployment\n- Network partition between regions\n- Need to decide: Availability vs Consistency',
    'Hint 1: CAP theorem: Choose 2 of 3 (Consistency, Availability, Partition Tolerance).\n---\nHint 2: Different strategies for different data types.\n---\nHint 3: Consider split-brain scenarios.',
    '## CAP Trade-offs:\n\n**CP (Consistency over Availability)**\n- Reject writes during partition\n- Example: Banking systems, inventory\n- Implementations: Etcd, Consul, ZooKeeper\n\n**AP (Availability over Consistency)**\n- Accept writes in both partitions\n- Reconcile conflicts later\n- Example: Social media posts, shopping carts\n- Implementations: Cassandra, DynamoDB\n\n**Strategies:**\n\n1. **Quorum Reads/Writes**\n   - W + R > N (W=write replicas, R=read replicas, N=total)\n   - Ensures consistency\n\n2. **Conflict Resolution**\n   - Last-Write-Wins (timestamp)\n   - Application-level merge\n   - Vector clocks for causality\n\n3. **Split-Brain Prevention**\n   - Majority quorum\n   - Witness/arbiter nodes\n   - Fencing tokens\n\n4. **Circuit Breakers**\n   - Detect partition\n   - Fail fast\n   - Graceful degradation',
    'HARD',
    'system-design,cap-theorem,network-partition,distributed-systems'
);

-- System Design Problem 5
INSERT INTO problem (module_type, category, arena, title, description_markdown, hints_markdown, solution_explanation_markdown, difficulty, tags)
VALUES (
    'SYS_DESIGN',
    'GOOGLE',
    'SYSTEM_DESIGN',
    'Reducing Global API Latency',
    '# Global API Latency Optimization\n\nWhat steps would you take to reduce network latency for API calls made by users worldwide?\n\n**Current State:**\n- Single US data center\n- Users in Asia experience 300ms+ latency\n- API serves dynamic content',
    'Hint 1: CDN for static content, but what about dynamic?\n---\nHint 2: Edge computing and regional deployments.\n---\nHint 3: Caching strategies at multiple levels.',
    '## Latency Reduction Strategies:\n\n**1. CDN & Edge Locations**\n- CloudFlare, Fastly, CloudFront\n- Static assets at edge\n- Edge workers for dynamic content\n\n**2. Multi-Region Deployment**\n- Deploy services in multiple AWS/GCP regions\n- Route to nearest region (GeoDNS, Anycast)\n- Data locality challenges\n\n**3. Caching Layers**\n- **Browser cache**: Cache-Control headers\n- **CDN cache**: Cache dynamic content with short TTL\n- **Application cache**: Redis at edge\n- **Database cache**: Read replicas, query cache\n\n**4. Connection Optimization**\n- HTTP/2, HTTP/3 (QUIC)\n- Keep-Alive connections\n- Connection pooling\n- TCP Fast Open\n\n**5. Data Optimization**\n- Compress responses (gzip, Brotli)\n- Reduce payload size\n- GraphQL to fetch only needed data\n- Pagination for large datasets\n\n**6. Async & Batch Operations**\n- Webhooks instead of polling\n- Batch multiple API calls\n- Server-Sent Events (SSE) or WebSockets\n\n**7. Regional Data Replication**\n- Replicate frequently accessed data\n- Eventual consistency acceptable for many use cases',
    'MEDIUM',
    'system-design,latency,cdn,performance'
);

-- System Design Problem 6
INSERT INTO problem (module_type, category, arena, title, description_markdown, hints_markdown, solution_explanation_markdown, difficulty, tags)
VALUES (
    'SYS_DESIGN',
    'AMAZON',
    'SYSTEM_DESIGN',
    '24/7 High Availability with Datacenter Outage',
    '# High Availability Design\n\nYour service must be available 24/7. How do you design it to tolerate a data center outage?\n\n**Requirements:**\n- 99.99% uptime (52 minutes downtime/year)\n- Automatic failover\n- No data loss',
    'Hint 1: Multi-AZ and multi-region deployments.\n---\nHint 2: Active-active vs active-passive.\n---\nHint 3: Health checks and automatic failover.',
    '## High Availability Architecture:\n\n**1. Multi-AZ Deployment**\n- Deploy across multiple Availability Zones\n- Synchronous replication within region\n- Load balancer distributes traffic\n\n**2. Multi-Region (Active-Active)**\n- Traffic served from multiple regions\n- GeoDNS routes to nearest healthy region\n- Higher complexity but no failover delay\n\n**3. Multi-Region (Active-Passive)**\n- Primary region serves traffic\n- Standby region ready for failover\n- Lower cost, but failover delay\n\n**4. Database Replication**\n- **Synchronous**: No data loss, higher latency\n- **Asynchronous**: Lower latency, potential data loss\n- **Semi-synchronous**: Hybrid approach\n\n**5. Health Checks & Monitoring**\n- Deep health checks (not just ping)\n- Check dependencies (DB, cache, downstream services)\n- Circuit breakers for cascading failures\n\n**6. Automated Failover**\n- Route53 health checks\n- AWS Auto Scaling Groups\n- Kubernetes ReplicaSets\n- Avoid split-brain with quorum\n\n**7. Stateless Services**\n- Store state externally (DB, Redis)\n- Any instance can handle any request\n- Easy to scale and replace\n\n**8. Chaos Engineering**\n- Regularly test failover\n- Chaos Monkey, Gremlin\n- Game days',
    'HARD',
    'system-design,high-availability,fault-tolerance,disaster-recovery'
);

-- Continue with more System Design problems (abbreviated for space)

INSERT INTO problem (module_type, category, arena, title, description_markdown, hints_markdown, solution_explanation_markdown, difficulty, tags) VALUES
('SYS_DESIGN', 'META', 'SYSTEM_DESIGN', 'Preventing Cascading Failures', '# Cascading Failure Prevention\n\nIf a critical microservice goes down, how do you prevent the entire system from failing?', 'Hint 1: Circuit breakers and bulkheads.\n---\nHint 2: Timeouts and retries with backoff.\n---\nHint 3: Graceful degradation.', '## Prevention Strategies:\n\n**1. Circuit Breaker Pattern**\n- Hystrix, Resilience4j\n- Open: Stop calling failed service\n- Half-open: Test if service recovered\n- Closed: Normal operation\n\n**2. Bulkhead Pattern**\n- Isolate thread pools\n- One service failure doesn''t exhaust all threads\n\n**3. Timeouts**\n- Set aggressive timeouts\n- Don''t wait forever\n- Fail fast\n\n**4. Retry with Backoff**\n- Exponential backoff\n- Jitter to avoid thundering herd\n- Maximum retry limit\n\n**5. Rate Limiting**\n- Protect downstream services\n- Token bucket, leaky bucket\n- Per-user and global limits\n\n**6. Load Shedding**\n- Drop low-priority requests\n- Preserve core functionality\n\n**7. Graceful Degradation**\n- Serve stale data from cache\n- Disable non-critical features\n- Show meaningful errors', 'HARD', 'system-design,resilience,circuit-breaker,fault-tolerance'),

('SYS_DESIGN', 'GOOGLE', 'SYSTEM_DESIGN', 'Graceful Degradation Strategy', '# Graceful Degradation\n\nHow can you introduce graceful degradation so a partial failure doesn''t take down the whole system?', 'Hint 1: Feature flags and tiered features.\n---\nHint 2: Fallback mechanisms.\n---\nHint 3: Priority queues.', '## Graceful Degradation Techniques:\n\n**1. Feature Tiers**\n- Critical: Must work (login, checkout)\n- Important: Should work (recommendations)\n- Nice-to-have: Can fail (animations)\n\n**2. Fallback Mechanisms**\n- Cached data instead of real-time\n- Default values\n- Simplified UI\n\n**3. Feature Flags**\n- LaunchDarkly, Split.io\n- Disable features dynamically\n- A/B testing and gradual rollout\n\n**4. Service Mesh**\n- Istio, Linkerd\n- Traffic shaping\n- Automatic retries\n- Circuit breaking\n\n**5. Priority Queues**\n- VIP users get priority\n- Critical operations first\n- Background jobs delayed\n\n**6. Async Processing**\n- Queue non-critical work\n- Process when system recovers', 'MEDIUM', 'system-design,graceful-degradation,resilience'),

('SYS_DESIGN', 'AMAZON', 'SYSTEM_DESIGN', 'Exactly-Once Message Processing', '# Exactly-Once Message Delivery\n\nHow do you guarantee exactly-once message processing in a distributed queue?\n\n**Challenges:**\n- At-least-once is easy (retry until success)\n- At-most-once is easy (don''t retry)\n- Exactly-once is hard (network can duplicate)', 'Hint 1: Idempotency is key.\n---\nHint 2: Unique message IDs and deduplication.\n---\nHint 3: Two-phase commit or saga pattern.', '## Exactly-Once Strategies:\n\n**1. Idempotent Operations**\n- Design operations to be safely retried\n- Same input → same result, no side effects\n- Example: SET vs INCREMENT\n\n**2. Deduplication**\n- Unique message ID\n- Track processed IDs (Redis, DB)\n- Reject duplicates\n- TTL for cleanup\n\n**3. Transactional Outbox**\n- Write message and business logic in same transaction\n- Separate process publishes from outbox\n- Guaranteed consistency\n\n**4. Two-Phase Commit (2PC)**\n- Prepare phase: All participants ready\n- Commit phase: All commit or all rollback\n- Blocking and slow\n\n**5. Saga Pattern**\n- Sequence of local transactions\n- Compensating transactions for rollback\n- Eventual consistency\n\n**6. Kafka Exactly-Once**\n- Transactional writes\n- Idempotent producers\n- Read committed isolation\n\n**Trade-offs:**\n- Perfect exactly-once is impossible (network duplicates)\n- Practical: Idempotency + deduplication', 'HARD', 'system-design,messaging,distributed-systems,exactly-once'),

('SYS_DESIGN', 'META', 'SYSTEM_DESIGN', 'Design URL Shortener', '# URL Shortener Design\n\nDesign a URL shortening service like bit.ly.\n\n**Requirements:**\n- Shorten long URLs to 6-character codes\n- Redirect to original URL\n- 100M URLs/month\n- Low latency', 'Hint 1: Base62 encoding for compact IDs.\n---\nHint 2: Cache popular URLs.\n---\nHint 3: Consider collision handling.', '## Design:\n\n**1. Short URL Generation**\n- Auto-increment ID → Base62\n- MD5 hash → Take first 6 chars (check collisions)\n- Random ID with collision check\n\n**2. Storage**\n- **Relational DB**: id, short_url, long_url, created_at\n- **NoSQL**: Key-value (Redis, DynamoDB)\n- Index on short_url\n\n**3. Caching**\n- Redis for hot URLs\n- LRU eviction\n- 80/20 rule: Cache 20% most popular\n\n**4. API Design**\n- POST /shorten {longUrl} → {shortUrl}\n- GET /{shortCode} → 301 redirect\n\n**5. Analytics**\n- Click tracking\n- Async writes to analytics DB\n- Kafka/Kinesis stream\n\n**6. Scale**\n- Read-heavy: Cache + read replicas\n- Write: Shard by short code\n- CDN for redirects', 'MEDIUM', 'system-design,url-shortener,caching'),

('SYS_DESIGN', 'GOOGLE', 'SYSTEM_DESIGN', 'Design Rate Limiter', '# Rate Limiter Design\n\nDesign a rate limiter to prevent abuse (e.g., 100 requests per user per hour).', 'Hint 1: Token bucket or leaky bucket algorithm.\n---\nHint 2: Redis for distributed rate limiting.\n---\nHint 3: Consider different limits for different users.', '## Rate Limiting Algorithms:\n\n**1. Token Bucket**\n- Bucket holds tokens\n- Request consumes token\n- Tokens refill at constant rate\n- Allows bursts\n\n**2. Leaky Bucket**\n- Requests enter queue\n- Process at constant rate\n- Overflow requests rejected\n- Smooths bursts\n\n**3. Fixed Window**\n- Count requests in time window\n- Reset at window boundary\n- Simple but allows bursts at boundary\n\n**4. Sliding Window**\n- Count in rolling time window\n- More accurate than fixed\n- More expensive to compute\n\n**Implementation:**\n\n```python\n# Redis Lua script for token bucket\nlocal tokens = redis.call(''get'', KEYS[1])\nif not tokens then\n  tokens = ARGV[1]  # capacity\nend\n\nif tokens > 0 then\n  redis.call(''set'', KEYS[1], tokens - 1)\n  redis.call(''expire'', KEYS[1], ARGV[2])  # window\n  return 1\nelse\n  return 0\nend\n```\n\n**5. Hierarchical Limits**\n- Per-user: 100/hour\n- Per-API-key: 1000/hour\n- Global: 1M/hour\n\n**6. Distributed Rate Limiting**\n- Redis with Lua scripts (atomic)\n- Hazelcast for in-memory grid\n- Eventual consistency acceptable', 'MEDIUM', 'system-design,rate-limiting,throttling'),

('SYS_DESIGN', 'AMAZON', 'SYSTEM_DESIGN', 'Design Chat System', '# Chat System Design\n\nDesign a real-time chat system like Slack or WhatsApp.\n\n**Requirements:**\n- 1-to-1 and group chat\n- Real-time message delivery\n- Message history\n- Online/offline status', 'Hint 1: WebSockets for real-time communication.\n---\nHint 2: Message queue for reliability.\n---\nHint 3: Shard by user or conversation.', '## Design:\n\n**1. Real-time Communication**\n- WebSockets for bidirectional\n- Long polling as fallback\n- Server-Sent Events for one-way\n\n**2. Architecture**\n- **Chat servers**: Handle WebSocket connections\n- **Message queue**: Kafka, RabbitMQ for reliability\n- **Presence service**: Redis for online status\n- **Message store**: Cassandra for history\n\n**3. Message Flow**\n1. User sends message via WebSocket\n2. Chat server publishes to message queue\n3. Queue delivers to recipient''s chat server\n4. Chat server pushes to recipient\n5. Persist to message store\n\n**4. Group Chat**\n- Fan-out on write: Send to all members\n- Fan-out on read: Store once, read by all\n- Hybrid: Small groups (write), large groups (read)\n\n**5. Message History**\n- Cassandra: Partition by conversation_id\n- Pagination for loading\n- Search with Elasticsearch\n\n**6. Presence Service**\n- Heartbeat from clients\n- Redis with expiry\n- Pub/Sub for presence updates\n\n**7. File Sharing**\n- Upload to S3\n- Share signed URL\n- Thumbnail generation\n\n**8. Push Notifications**\n- FCM (Firebase), APNS\n- For offline users', 'HARD', 'system-design,chat,websockets,real-time'),

('SYS_DESIGN', 'META', 'SYSTEM_DESIGN', 'Design News Feed', '# News Feed Design\n\nDesign a news feed system like Facebook or Twitter.\n\n**Requirements:**\n- Users follow other users\n- See posts from followed users\n- Chronological or ranked feed\n- High read:write ratio', 'Hint 1: Fan-out on write vs fan-out on read.\n---\nHint 2: Cache for hot users.\n---\nHint 3: Pre-compute feeds.', '## Design:\n\n**1. Fan-out Strategies**\n\n**Fan-out on Write (Push):**\n- When user posts, push to all followers'' feeds\n- Fast reads, slow writes\n- Good for users with few followers\n- Celebrity problem: Millions of followers\n\n**Fan-out on Read (Pull):**\n- Fetch posts from followed users on read\n- Fast writes, slow reads\n- Good for celebrities\n\n**Hybrid:**\n- Push for regular users\n- Pull for celebrities\n- Cache celebrity posts\n\n**2. Data Model**\n```\nPost: post_id, user_id, content, created_at\nFollow: follower_id, followee_id\nFeed: user_id, post_id, created_at\n```\n\n**3. Feed Generation**\n- Pre-compute feeds asynchronously\n- Store in Redis (sorted set by timestamp)\n- Merge celebrity posts on read\n\n**4. Ranking Algorithm**\n- Chronological (Twitter)\n- Engagement-based (Facebook)\n- ML model for personalization\n\n**5. Pagination**\n- Cursor-based (not offset)\n- Store last_seen_post_id\n\n**6. Real-time Updates**\n- WebSocket or long polling\n- Push new posts to active users\n\n**7. Scale**\n- Shard by user_id\n- Cache hot feeds\n- CDN for media', 'HARD', 'system-design,news-feed,social-media'),

('SYS_DESIGN', 'GOOGLE', 'SYSTEM_DESIGN', 'Design Video Streaming', '# Video Streaming Service\n\nDesign a video streaming service like YouTube or Netflix.', 'Hint 1: Adaptive bitrate streaming.\n---\nHint 2: CDN for content delivery.\n---\nHint 3: Transcoding pipeline.', '## Design:\n\n**1. Video Upload & Processing**\n- Upload to S3\n- Transcoding: ffmpeg, AWS MediaConvert\n- Multiple resolutions (360p, 720p, 1080p, 4K)\n- Multiple codecs (H.264, H.265, VP9, AV1)\n\n**2. Adaptive Bitrate Streaming**\n- HLS (HTTP Live Streaming)\n- DASH (Dynamic Adaptive Streaming)\n- Segment video into chunks (2-10 seconds)\n- Manifest file with quality levels\n- Player adapts based on bandwidth\n\n**3. CDN**\n- Distribute videos globally\n- CloudFront, Akamai, Cloudflare\n- Edge caching\n- Reduce origin load\n\n**4. Video Player**\n- HTML5 video\n- JavaScript player (Video.js, Shaka Player)\n- DRM for premium content\n\n**5. Recommendations**\n- Collaborative filtering\n- Content-based filtering\n- ML model trained on watch history\n\n**6. Analytics**\n- Watch time, completion rate\n- Buffering events\n- Quality switches\n- Kafka → Analytics DB\n\n**7. Live Streaming**\n- RTMP ingest\n- Low latency: WebRTC, SRT\n- Transcoding in real-time\n\n**8. Storage**\n- S3 for videos\n- Metadata in DB (title, description, views)\n- Comments in NoSQL (Cassandra)', 'HARD', 'system-design,video-streaming,cdn,media'),

('SYS_DESIGN', 'AMAZON', 'SYSTEM_DESIGN', 'Design Search Autocomplete', '# Search Autocomplete\n\nDesign a search autocomplete system like Google search suggestions.', 'Hint 1: Trie data structure.\n---\nHint 2: Pre-compute popular queries.\n---\nHint 3: Cache suggestions.', '## Design:\n\n**1. Trie (Prefix Tree)**\n- Store queries in trie\n- Each node has count (popularity)\n- Search: Traverse prefix, return top K\n- Space-efficient for common prefixes\n\n**2. Data Collection**\n- Log search queries\n- Aggregate counts daily/hourly\n- Weight by recency\n\n**3. Storage**\n- **In-memory Trie**: Fast, limited by RAM\n- **Database**: Scalable, slower\n- Hybrid: Trie for popular, DB for long tail\n\n**4. Ranking**\n- Popularity (search count)\n- Recency (time decay)\n- Personalization (user history)\n- Location-based\n\n**5. Caching**\n- Cache top suggestions per prefix\n- Redis with TTL\n- Pre-compute popular prefixes\n\n**6. Update Strategy**\n- Batch updates (hourly/daily)\n- Not real-time (stale acceptable)\n- Rebuild trie periodically\n\n**7. API**\n- GET /autocomplete?q=prefix&limit=10\n- Returns JSON: [{query, count}]\n\n**8. Scale**\n- Shard by prefix (a-m, n-z)\n- Replicate trie across servers\n- CDN for popular prefixes', 'MEDIUM', 'system-design,autocomplete,trie,search'),

('SYS_DESIGN', 'META', 'SYSTEM_DESIGN', 'Design Notification System', '# Notification System\n\nDesign a notification system supporting email, SMS, and push notifications.', 'Hint 1: Message queue for reliability.\n---\nHint 2: Priority and rate limiting.\n---\nHint 3: Template system.', '## Design:\n\n**1. Architecture**\n- **API**: Enqueue notification\n- **Queue**: Kafka, RabbitMQ\n- **Workers**: Process queue\n- **Providers**: SendGrid, Twilio, FCM\n\n**2. Notification Types**\n- Email (SendGrid, AWS SES)\n- SMS (Twilio, SNS)\n- Push (FCM, APNS)\n- In-app\n- Webhooks\n\n**3. Priority Levels**\n- Critical: Immediate (security alerts)\n- High: Fast (OTP)\n- Normal: Best effort\n- Low: Batch (newsletters)\n\n**4. Rate Limiting**\n- Per-user limits (don''t spam)\n- Per-provider limits (API quotas)\n- Token bucket algorithm\n\n**5. Template System**\n- Store templates in DB\n- Variables: {{user_name}}, {{amount}}\n- Localization (i18n)\n\n**6. Retry Logic**\n- Exponential backoff\n- Dead letter queue\n- Max retries\n\n**7. User Preferences**\n- Opt-in/opt-out per channel\n- Quiet hours\n- Frequency caps\n\n**8. Tracking**\n- Delivery status\n- Open rates (email)\n- Click-through rates\n- Analytics dashboard', 'MEDIUM', 'system-design,notifications,messaging'),

('SYS_DESIGN', 'GOOGLE', 'SYSTEM_DESIGN', 'Design Distributed Cache', '# Distributed Cache\n\nDesign a distributed caching system like Memcached or Redis.', 'Hint 1: Consistent hashing for distribution.\n---\nHint 2: Replication for availability.\n---\nHint 3: Eviction policies (LRU, LFU).', '## Design:\n\n**1. Consistent Hashing**\n- Minimize key redistribution on node add/remove\n- Virtual nodes for balance\n- Hash ring\n\n**2. Data Structure**\n- HashMap for fast lookup\n- Doubly-linked list for LRU\n- Combined: O(1) get, set, evict\n\n**3. Eviction Policies**\n- **LRU**: Least Recently Used\n- **LFU**: Least Frequently Used\n- **TTL**: Time To Live\n- **Random**: Simple, good enough\n\n**4. Replication**\n- Master-slave replication\n- Async for performance\n- Quorum for consistency\n\n**5. Sharding**\n- Partition data across nodes\n- Each node handles subset\n- Client-side sharding or proxy\n\n**6. Availability**\n- Replica sets\n- Sentinel for failover (Redis)\n- Health checks\n\n**7. Persistence (Optional)**\n- Snapshots (RDB)\n- Append-only file (AOF)\n- Hybrid\n\n**8. API**\n- GET key\n- SET key value [EX seconds]\n- DELETE key\n- INCR, DECR\n- EXPIRE key seconds', 'HARD', 'system-design,caching,distributed-systems'),

('SYS_DESIGN', 'AMAZON', 'SYSTEM_DESIGN', 'Design Web Crawler', '# Web Crawler Design\n\nDesign a web crawler that indexes billions of web pages.', 'Hint 1: BFS with distributed queue.\n---\nHint 2: Politeness (robots.txt, rate limiting).\n---\nHint 3: Deduplication and URL frontier.', '## Design:\n\n**1. Components**\n- **URL Frontier**: Queue of URLs to crawl\n- **Fetcher**: Downloads pages\n- **Parser**: Extracts links\n- **Storage**: Stores pages\n- **Deduplicator**: Avoids revisiting\n\n**2. URL Frontier**\n- Priority queue (important sites first)\n- FIFO queue per host (politeness)\n- Kafka or Redis for distribution\n\n**3. Politeness**\n- robots.txt compliance\n- Crawl delay per host\n- Rate limiting\n- User-Agent header\n\n**4. Deduplication**\n- URL normalization (http/https, trailing slash)\n- Bloom filter for visited URLs\n- Content fingerprinting (MD5, SimHash)\n\n**5. DNS Resolution**\n- Cache DNS lookups\n- Async DNS resolution\n- Avoid DNS rate limiting\n\n**6. Content Processing**\n- Parse HTML (BeautifulSoup, lxml)\n- Extract text for indexing\n- Detect language\n- Extract metadata\n\n**7. Storage**\n- **Page store**: S3, HDFS\n- **Index**: Elasticsearch\n- **Metadata**: Cassandra\n\n**8. Scale**\n- Distributed workers\n- Shard by domain\n- Incremental crawling\n- Prioritize fresh content', 'HARD', 'system-design,web-crawler,distributed-systems'),

('SYS_DESIGN', 'META', 'SYSTEM_DESIGN', 'Design Ride-Sharing Service', '# Ride-Sharing Service\n\nDesign a ride-sharing service like Uber or Lyft.', 'Hint 1: Geospatial indexing (quadtree, geohash).\n---\nHint 2: WebSockets for real-time updates.\n---\nHint 3: Pricing and matching algorithms.', '## Design:\n\n**1. Core Features**\n- Driver/rider matching\n- Real-time location tracking\n- Dynamic pricing (surge)\n- Payment processing\n- Ratings\n\n**2. Geospatial Indexing**\n- **Geohash**: Encode lat/lon to string\n- **QuadTree**: Hierarchical spatial index\n- **S2 Geometry**: Google''s library\n- Redis with geo commands\n\n**3. Driver Matching**\n1. Find nearby drivers (geospatial query)\n2. Filter by availability, rating\n3. Estimate ETA\n4. Send request to closest\n5. Timeout and try next\n\n**4. Real-time Location**\n- Drivers send location every 5 seconds\n- Update in Redis (geospatial)\n- Publish to rider via WebSocket\n\n**5. Trip State Machine**\n- REQUESTED → ACCEPTED → ARRIVED → IN_PROGRESS → COMPLETED\n- Store in DB, cache in Redis\n\n**6. Dynamic Pricing**\n- Supply/demand ratio\n- Time of day, weather\n- Special events\n- ML model\n\n**7. Payment**\n- Stripe, Braintree\n- Store payment methods\n- Process after trip\n- Split for ride-sharing\n\n**8. Notifications**\n- Driver arriving\n- Trip started/ended\n- Push notifications\n\n**9. Scale**\n- Shard by geography\n- Separate services: matching, tracking, payment\n- Event-driven architecture', 'HARD', 'system-design,ride-sharing,geospatial,real-time');

-- Additional 30 System Design problems (shorter descriptions)

INSERT INTO problem (module_type, category, arena, title, description_markdown, hints_markdown, solution_explanation_markdown, difficulty, tags) VALUES
('SYS_DESIGN', 'GOOGLE', 'SYSTEM_DESIGN', 'Design Dropbox', '# File Storage System\n\nDesign a file storage and sync service like Dropbox.', 'Hint 1: Chunking and deduplication.\n---\nHint 2: Sync algorithm.\n---\nHint 3: Conflict resolution.', '## Key Components:\n- Chunking (4MB blocks)\n- Metadata service\n- Sync service\n- Block storage (S3)\n- Delta sync\n- Version history\n- Conflict resolution (operational transform)', 'HARD', 'system-design,file-storage,sync'),

('SYS_DESIGN', 'AMAZON', 'SYSTEM_DESIGN', 'Design Ticketmaster', '# Ticket Booking System\n\nDesign a ticket booking system handling flash sales.', 'Hint 1: Inventory management with concurrency.\n---\nHint 2: Queuing system.\n---\nHint 3: Prevent double booking.', '## Key Solutions:\n- Pessimistic locking for inventory\n- Queue system for fairness\n- Virtual waiting room\n- Redis for seat locks\n- ACID transactions\n- Timeout for held seats', 'HARD', 'system-design,ticketing,concurrency'),

('SYS_DESIGN', 'META', 'SYSTEM_DESIGN', 'Design Instagram', '# Photo Sharing Service\n\nDesign Instagram.', 'Hint 1: Image processing and storage.\n---\nHint 2: News feed.\n---\nHint 3: Followers graph.', '## Key Components:\n- Image upload → S3\n- Image processing (resize, filters)\n- News feed (fan-out)\n- Graph DB for followers\n- CDN for images\n- Sharding by user_id', 'HARD', 'system-design,social-media,photo-sharing'),

('SYS_DESIGN', 'GOOGLE', 'SYSTEM_DESIGN', 'Design Zoom', '# Video Conferencing System\n\nDesign a video conferencing system.', 'Hint 1: WebRTC for peer-to-peer.\n---\nHint 2: SFU (Selective Forwarding Unit).\n---\nHint 3: Recording and transcoding.', '## Key Components:\n- WebRTC for video/audio\n- TURN server for NAT traversal\n- SFU for multi-party\n- Recording to S3\n- Screen sharing\n- Chat via WebSocket', 'HARD', 'system-design,video-conferencing,webrtc'),

('SYS_DESIGN', 'AMAZON', 'SYSTEM_DESIGN', 'Design Amazon S3', '# Object Storage System\n\nDesign an object storage system like S3.', 'Hint 1: Distributed storage with replication.\n---\nHint 2: Metadata service.\n---\nHint 3: Eventual consistency.', '## Key Components:\n- Metadata in DB\n- Data nodes (commodity hardware)\n- Replication (3 copies)\n- Consistent hashing\n- Erasure coding\n- Versioning', 'HARD', 'system-design,storage,distributed-systems'),

('SYS_DESIGN', 'META', 'SYSTEM_DESIGN', 'Design Yelp', '# Location-Based Service\n\nDesign Yelp.', 'Hint 1: Geospatial search.\n---\nHint 2: Reviews and ratings.\n---\nHint 3: Elasticsearch for text search.', '## Key Components:\n- Geospatial index (quadtree)\n- Elasticsearch for search\n- Review storage\n- Aggregated ratings\n- CDN for photos\n- Caching for popular locations', 'MEDIUM', 'system-design,location-based,search'),

('SYS_DESIGN', 'GOOGLE', 'SYSTEM_DESIGN', 'Design Google Docs', '# Collaborative Document Editing\n\nDesign Google Docs.', 'Hint 1: Operational Transformation (OT).\n---\nHint 2: WebSocket for real-time.\n---\nHint 3: Conflict-free resolution.', '## Key Solutions:\n- Operational Transformation\n- CRDT (Conflict-free Replicated Data Type)\n- WebSocket for real-time\n- Version history\n- Cursor positions\n- Document storage', 'HARD', 'system-design,collaborative-editing,ot,crdt'),

('SYS_DESIGN', 'AMAZON', 'SYSTEM_DESIGN', 'Design Amazon Prime Video', '# Video on Demand\n\nDesign a VOD platform.', 'Hint 1: Similar to YouTube/Netflix.\n---\nHint 2: DRM for premium content.\n---\nHint 3: Recommendations.', '## Key Components:\n- Same as Netflix/YouTube\n- DRM (Widevine, FairPlay)\n- Subscription management\n- Download for offline\n- Multiple profiles\n- Parental controls', 'HARD', 'system-design,video,vod'),

('SYS_DESIGN', 'META', 'SYSTEM_DESIGN', 'Design Facebook Messenger', '# Messaging System\n\nDesign Facebook Messenger.', 'Hint 1: Same as chat system.\n---\nHint 2: Add features: stories, calls.\n---\nHint 3: End-to-end encryption.', '## Key Components:\n- Chat system base\n- Voice/video calls (WebRTC)\n- Stories (time-limited)\n- E2E encryption (Signal Protocol)\n- Message reactions\n- Read receipts', 'HARD', 'system-design,messaging,chat'),

('SYS_DESIGN', 'GOOGLE', 'SYSTEM_DESIGN', 'Design Google Calendar', '# Calendar System\n\nDesign a calendar system with shared events.', 'Hint 1: Event storage with recurrence.\n---\nHint 2: Conflict detection.\n---\nHint 3: Notifications and reminders.', '## Key Components:\n- Event storage (start, end, recurrence)\n- Conflict detection\n- Sharing and permissions\n- Reminders (cron, queue)\n- Time zone handling\n- CalDAV protocol', 'MEDIUM', 'system-design,calendar'),

('SYS_DESIGN', 'AMAZON', 'SYSTEM_DESIGN', 'Design Content Delivery Network', '# CDN Design\n\nDesign a CDN.', 'Hint 1: Edge locations globally.\n---\nHint 2: Cache with TTL.\n---\nHint 3: Origin pull vs push.', '## Key Components:\n- Edge servers globally\n- Cache with LRU/LFU\n- Origin pull on cache miss\n- GeoDNS for routing\n- SSL termination at edge\n- Purge API\n- Analytics', 'HARD', 'system-design,cdn,caching'),

('SYS_DESIGN', 'META', 'SYSTEM_DESIGN', 'Design Reddit', '# Discussion Forum\n\nDesign Reddit.', 'Hint 1: Voting and ranking.\n---\nHint 2: Nested comments.\n---\nHint 3: Subreddits as sharding key.', '## Key Components:\n- Post and comment storage\n- Voting (upvote/downvote)\n- Ranking algorithm (hot, top, new)\n- Nested comments (tree structure)\n- Subreddit isolation\n- Moderation tools', 'MEDIUM', 'system-design,forum,reddit'),

('SYS_DESIGN', 'GOOGLE', 'SYSTEM_DESIGN', 'Design Google Maps', '# Maps and Navigation\n\nDesign Google Maps.', 'Hint 1: Graph for roads.\n---\nHint 2: Dijkstra/A* for routing.\n---\nHint 3: Real-time traffic.', '## Key Components:\n- Road graph (nodes, edges)\n- Routing (A* algorithm)\n- Real-time traffic (crowdsourced)\n- Tile-based map rendering\n- Geocoding\n- POI search\n- ETA calculation', 'HARD', 'system-design,maps,navigation,graph'),

('SYS_DESIGN', 'AMAZON', 'SYSTEM_DESIGN', 'Design Payment System', '# Payment Processing\n\nDesign a payment system.', 'Hint 1: Idempotency is critical.\n---\nHint 2: Two-phase commit.\n---\nHint 3: Reconciliation and auditing.', '## Key Components:\n- Payment gateway integration\n- Idempotency keys\n- Two-phase commit\n- Wallet/balance management\n- Transaction log\n- Reconciliation\n- Fraud detection\n- PCI compliance', 'HARD', 'system-design,payment,transactions'),

('SYS_DESIGN', 'META', 'SYSTEM_DESIGN', 'Design Ad Click Aggregator', '# Real-time Analytics\n\nDesign system to aggregate ad click events in real-time.', 'Hint 1: Stream processing (Kafka, Flink).\n---\nHint 2: Time-windowed aggregations.\n---\nHint 3: OLAP for queries.', '## Key Components:\n- Kafka for event stream\n- Flink/Spark Streaming\n- Time windows (tumbling, sliding)\n- Aggregations (count, sum)\n- Store in Druid/ClickHouse\n- Real-time dashboard', 'HARD', 'system-design,real-time-analytics,streaming'),

('SYS_DESIGN', 'GOOGLE', 'SYSTEM_DESIGN', 'Design Google Search', '# Search Engine\n\nDesign a web search engine.', 'Hint 1: Crawling → Indexing → Ranking.\n---\nHint 2: Inverted index.\n---\nHint 3: PageRank algorithm.', '## Key Components:\n- Web crawler\n- Inverted index (term → doc IDs)\n- Ranking (PageRank, relevance)\n- Query processing\n- Caching\n- Distributed index\n- Autocomplete', 'HARD', 'system-design,search-engine,indexing'),

('SYS_DESIGN', 'AMAZON', 'SYSTEM_DESIGN', 'Design Leaderboard System', '# Gaming Leaderboard\n\nDesign a leaderboard for millions of users.', 'Hint 1: Redis Sorted Sets.\n---\nHint 2: Sharding by score range.\n---\nHint 3: Real-time updates.', '## Key Solutions:\n- Redis Sorted Set (ZADD, ZRANK, ZRANGE)\n- Sharding by score range\n- Approximate ranks for distant users\n- Time-windowed leaderboards\n- Caching top players\n- Batch updates', 'MEDIUM', 'system-design,leaderboard,gaming'),

('SYS_DESIGN', 'META', 'SYSTEM_DESIGN', 'Design OAuth 2.0 System', '# Authentication Service\n\nDesign an OAuth 2.0 authentication system.', 'Hint 1: Authorization code flow.\n---\nHint 2: JWT tokens.\n---\nHint 3: Refresh tokens.', '## Key Components:\n- Authorization server\n- Resource server\n- Client registration\n- Authorization code flow\n- Access tokens (JWT)\n- Refresh tokens\n- Scope-based permissions\n- Token revocation', 'HARD', 'system-design,oauth,authentication'),

('SYS_DESIGN', 'GOOGLE', 'SYSTEM_DESIGN', 'Design Parking Lot System', '# Parking Lot Design\n\nDesign a parking lot management system.', 'Hint 1: Real-time availability.\n---\nHint 2: Pricing tiers.\n---\nHint 3: Reservation system.', '## Key Components:\n- Spot availability tracking\n- Vehicle type (compact, large, handicapped)\n- Entry/exit tracking\n- Payment integration\n- Pricing algorithm\n- Mobile app\n- Sensors for occupancy', 'EASY', 'system-design,parking'),

('SYS_DESIGN', 'AMAZON', 'SYSTEM_DESIGN', 'Design Library Management System', '# Library System\n\nDesign a library management system.', 'Hint 1: Book inventory.\n---\nHint 2: Check-in/check-out.\n---\nHint 3: Reservation and waitlist.', '## Key Components:\n- Book catalog\n- Inventory management\n- Check-out/return\n- Late fees\n- Reservation system\n- Search (by title, author, ISBN)\n- User accounts', 'EASY', 'system-design,library'),

('SYS_DESIGN', 'META', 'SYSTEM_DESIGN', 'Design Hotel Booking System', '# Hotel Reservation\n\nDesign a hotel booking system like Booking.com.', 'Hint 1: Room inventory with concurrency.\n---\nHint 2: Overbooking strategy.\n---\nHint 3: Pricing engine.', '## Key Components:\n- Room inventory\n- Booking with locking\n- Overbooking (airlines do this)\n- Pricing (dynamic, seasonal)\n- Search and filters\n- Payments\n- Cancellations and refunds', 'MEDIUM', 'system-design,booking,hotel'),

('SYS_DESIGN', 'GOOGLE', 'SYSTEM_DESIGN', 'Design Elevator System', '# Elevator Control System\n\nDesign an elevator control system for a building.', 'Hint 1: Scheduling algorithm (SCAN, LOOK).\n---\nHint 2: Priority requests.\n---\nHint 3: Load balancing.', '## Key Components:\n- Request queue per elevator\n- SCAN algorithm (move in direction)\n- Load balancing (assign to nearest)\n- Priority (fire, emergency)\n- Capacity limits\n- Real-time status', 'EASY', 'system-design,elevator,scheduling'),

('SYS_DESIGN', 'AMAZON', 'SYSTEM_DESIGN', 'Design Stock Exchange', '# Trading System\n\nDesign a stock exchange trading system.', 'Hint 1: Order matching engine.\n---\nHint 2: Priority queue (price-time).\n---\nHint 3: High throughput, low latency.', '## Key Components:\n- Order book (buy/sell)\n- Matching engine (FIFO at price level)\n- Market vs limit orders\n- Order book as sorted tree\n- Sub-millisecond latency\n- ACID transactions\n- Audit trail', 'HARD', 'system-design,trading,finance'),

('SYS_DESIGN', 'META', 'SYSTEM_DESIGN', 'Design Spotify', '# Music Streaming Service\n\nDesign Spotify.', 'Hint 1: Similar to video streaming.\n---\nHint 2: Playlist management.\n---\nHint 3: Recommendations.', '## Key Components:\n- Audio streaming (similar to video)\n- Playlists and favorites\n- Collaborative playlists\n- Recommendations (collaborative filtering)\n- Lyrics sync\n- Offline mode\n- Social features', 'HARD', 'system-design,music-streaming'),

('SYS_DESIGN', 'GOOGLE', 'SYSTEM_DESIGN', 'Design API Gateway', '# API Gateway Design\n\nDesign an API Gateway.', 'Hint 1: Routing and load balancing.\n---\nHint 2: Authentication and rate limiting.\n---\nHint 3: Request/response transformation.', '## Key Components:\n- Routing to microservices\n- Load balancing\n- Authentication (JWT)\n- Rate limiting\n- Request/response transformation\n- Caching\n- Circuit breaker\n- Logging and monitoring', 'MEDIUM', 'system-design,api-gateway,microservices'),

('SYS_DESIGN', 'AMAZON', 'SYSTEM_DESIGN', 'Design Metrics Monitoring System', '# Metrics and Monitoring\n\nDesign a metrics monitoring system like Datadog or Prometheus.', 'Hint 1: Time-series database.\n---\nHint 2: Aggregation and rollup.\n---\nHint 3: Alerting rules.', '## Key Components:\n- Metrics collection (push/pull)\n- Time-series DB (Prometheus, InfluxDB)\n- Aggregation and downsampling\n- Query language (PromQL)\n- Dashboards (Grafana)\n- Alerting (rules engine)\n- Retention policies', 'HARD', 'system-design,monitoring,metrics'),

('SYS_DESIGN', 'META', 'SYSTEM_DESIGN', 'Design Email Service', '# Email Service\n\nDesign an email service like Gmail.', 'Hint 1: Storage and indexing.\n---\nHint 2: Search.\n---\nHint 3: Spam filtering.', '## Key Components:\n- Email storage (S3, HDFS)\n- Metadata in DB\n- Full-text search (Elasticsearch)\n- Spam filtering (ML)\n- SMTP/IMAP/POP3\n- Attachments handling\n- Labels and folders\n- Threading', 'HARD', 'system-design,email'),

('SYS_DESIGN', 'GOOGLE', 'SYSTEM_DESIGN', 'Design Job Scheduler', '# Distributed Job Scheduler\n\nDesign a job scheduler like Kubernetes CronJob or Airflow.', 'Hint 1: DAG for job dependencies.\n---\nHint 2: Priority queue.\n---\nHint 3: Retry and failure handling.', '## Key Components:\n- Job queue (priority)\n- Worker pool\n- DAG for dependencies\n- Cron expressions\n- Retry logic\n- Dead letter queue\n- Monitoring and logs\n- Distributed locking', 'HARD', 'system-design,scheduler,distributed-systems'),

('SYS_DESIGN', 'AMAZON', 'SYSTEM_DESIGN', 'Design URL Shortener with Analytics', '# URL Shortener v2\n\nExtend URL shortener with analytics (clicks, referrers, etc.).', 'Hint 1: Async writes for analytics.\n---\nHint 2: Stream processing.\n---\nHint 3: OLAP for queries.', '## Key Components:\n- Base URL shortener\n- Click tracking (Kafka)\n- Stream processing (Flink)\n- Analytics DB (ClickHouse)\n- Dashboards\n- Real-time counters (Redis)\n- Geolocation', 'HARD', 'system-design,url-shortener,analytics');
