-- Advanced String Problems - 15 Problems (Pattern Not Obvious)

USE faang;

INSERT INTO problem (module_type, category, arena, title, description_markdown, hints_markdown, solution_explanation_markdown, difficulty, tags) VALUES

('ALGO', 'GOOGLE', 'STRINGS', 'Transform One String to Another', '# Transform One String to Another\n\nYou are given two strings `source` and `target`. Determine if you can transform `source` into `target` by performing the following operations any number of times:\n- Choose any character in `source` and change it to any other character\n- However, you cannot change a character if it would create a cycle\n\n**Example:**\n```\nInput: source = "aabcc", target = "ccdee"\nOutput: true\nExplanation: a→c, b→d, c→e\n\nInput: source = "leetcode", target = "codeleet"\nOutput: false\n```', 'Hint 1: Think about character mappings.\n---\nHint 2: Can one character map to multiple different characters?\n---\nHint 3: Check for cycles in the transformation graph.', '## Solution: Graph Detection\n\nThis is a graph problem disguised as a string problem. Build a directed graph where edges represent character transformations. Check:\n1. No character maps to multiple characters (one-to-one)\n2. No cycles exist (use DFS/Union-Find)\n3. If we need a temporary character, ensure one exists\n\nTime: O(n), Space: O(1)', 'HARD', 'string,graph,dfs'),

('ALGO', 'META', 'STRINGS', 'Decode Message Grid', '# Decode Message Grid\n\nGiven a 2D grid of characters, decode the hidden message by reading characters in a specific pattern:\n- Start at top-left\n- Move right until you hit a wall or boundary\n- Then move down one row\n- Then move left until boundary\n- Then move down one row\n- Repeat (zigzag pattern)\n\n**Example:**\n```\ngrid = [\n  [''H'',''E'',''L'',''L''],\n  [''W'',''O'',''R'',''L''],\n  [''D'',''!'',''!'',''O'']\n]\nOutput: "HELLOWORLD!"\n```', 'Hint 1: This is a matrix traversal pattern.\n---\nHint 2: Track direction changes.\n---\nHint 3: Use row parity to determine direction.', '## Solution: Matrix Zigzag Traversal\n\nIterate through rows:\n- Even rows: left to right\n- Odd rows: right to left\n\nTime: O(m*n), Space: O(1)', 'MEDIUM', 'string,matrix,traversal'),

('ALGO', 'AMAZON', 'STRINGS', 'Minimum Window Character Rearrangement', '# Minimum Window Character Rearrangement\n\nGiven two strings `s` and `pattern`, find the smallest window in `s` where characters can be rearranged to match `pattern`.\n\n**Example:**\n```\nInput: s = "cbaebabacd", pattern = "abc"\nOutput: "bac"\nExplanation: Can rearrange to "abc"\n```', 'Hint 1: Sliding window approach.\n---\nHint 2: Character frequency matching.\n---\nHint 3: Expand right, contract left.', '## Solution: Sliding Window + Hash Map\n\nUse sliding window with frequency map:\n1. Expand window until all pattern chars present\n2. Contract from left while maintaining validity\n3. Track minimum window\n\nTime: O(n), Space: O(1)', 'HARD', 'string,sliding-window,hash-table'),

('ALGO', 'GOOGLE', 'STRINGS', 'Count Palindrome Substrings with K Changes', '# Count Palindrome Substrings with K Changes\n\nGiven a string and integer k, count how many substrings can become palindromes by changing at most k characters.\n\n**Example:**\n```\nInput: s = "abcd", k = 2\nOutput: 7\nExplanation: All single chars + "ab"→"aa", "bc"→"bb", "cd"→"cc", "abc"→"aba"\n```', 'Hint 1: Try all substrings.\n---\nHint 2: For each substring, calculate minimum changes needed.\n---\nHint 3: Two pointer from edges to count mismatches.', '## Solution: Enumerate + Two Pointer\n\nFor each substring:\n- Use two pointers from edges\n- Count character mismatches\n- If mismatches ≤ k, it''s valid\n\nTime: O(n³), Space: O(1)', 'MEDIUM', 'string,two-pointers,palindrome'),

('ALGO', 'META', 'STRINGS', 'Shortest Palindrome by Prepending', '# Shortest Palindrome by Prepending\n\nGiven a string, find the shortest palindrome by only adding characters at the beginning.\n\n**Example:**\n```\nInput: s = "aacecaaa"\nOutput: "aaacecaaa"\n\nInput: s = "abcd"\nOutput: "dcbabcd"\n```', 'Hint 1: Find longest palindromic prefix.\n---\nHint 2: KMP algorithm helps here.\n---\nHint 3: Reverse string and find overlap.', '## Solution: KMP Pattern Matching\n\nFind longest prefix that is also a palindrome:\n1. Create string: s + "#" + reverse(s)\n2. Use KMP to find longest prefix-suffix match\n3. Prepend missing characters\n\nTime: O(n), Space: O(n)', 'HARD', 'string,kmp,palindrome'),

('ALGO', 'AMAZON', 'STRINGS', 'Word Break with Minimum Breaks', '# Word Break with Minimum Breaks\n\nGiven string s and dictionary, break s into dictionary words using minimum number of breaks. Return the minimum breaks needed.\n\n**Example:**\n```\nInput: s = "leetcode", dict = ["leet", "code", "lee", "tc", "ode"]\nOutput: 1 (one break: "leet|code")\n```', 'Hint 1: Dynamic programming.\n---\nHint 2: dp[i] = min breaks to break s[0..i]\n---\nHint 3: Try all possible last words.', '## Solution: DP\n\ndp[i] = minimum breaks for s[0..i]\nFor each position i, try all words ending at i\n\nTime: O(n² * m), Space: O(n)', 'HARD', 'string,dynamic-programming,trie'),

('ALGO', 'GOOGLE', 'STRINGS', 'Interleaved String Formation', '# Interleaved String Formation\n\nGiven three strings s1, s2, s3, check if s3 is formed by interleaving s1 and s2 while maintaining order.\n\n**Example:**\n```\nInput: s1 = "aabcc", s2 = "dbbca", s3 = "aadbbcbcac"\nOutput: true\n```', 'Hint 1: 2D dynamic programming.\n---\nHint 2: dp[i][j] = can form s3[0..i+j] from s1[0..i] and s2[0..j]\n---\nHint 3: Check if current char comes from s1 or s2.', '## Solution: 2D DP\n\ndp[i][j] represents if we can form s3[0..i+j-1] using first i chars of s1 and first j chars of s2.\n\nTime: O(m*n), Space: O(m*n)', 'HARD', 'string,dynamic-programming,2d-dp'),

('ALGO', 'META', 'STRINGS', 'Shortest Distance to Character', '# Shortest Distance to Character\n\nGiven string s and character c, return array where each element is the shortest distance from that index to character c.\n\n**Example:**\n```\nInput: s = "loveleetcode", c = ''e''\nOutput: [3,2,1,0,1,0,0,1,2,3,4,5]\n```', 'Hint 1: Two passes - left to right, then right to left.\n---\nHint 2: Track last seen position of c.\n---\nHint 3: Take minimum of both passes.', '## Solution: Two Pass\n\nFirst pass: track distance from left\nSecond pass: track distance from right\nTake minimum at each position\n\nTime: O(n), Space: O(n)', 'EASY', 'string,two-pointers,array'),

('ALGO', 'AMAZON', 'STRINGS', 'String Compression with Encoding', '# String Compression with Encoding\n\nCompress string by encoding consecutive characters. If compressed is longer, return original.\n\n**Example:**\n```\nInput: "aabcccccaaa"\nOutput: "a2b1c5a3"\n\nInput: "abcd"\nOutput: "abcd" (no compression)\n```', 'Hint 1: Two pointers to count runs.\n---\nHint 2: Build result string.\n---\nHint 3: Compare lengths at end.', '## Solution: Two Pointer Run Length\n\nCount consecutive chars, append to result\n\nTime: O(n), Space: O(n)', 'EASY', 'string,two-pointers'),

('ALGO', 'GOOGLE', 'STRINGS', 'Reorganize String with K Distance', '# Reorganize String with K Distance\n\nRearrange string so same characters are at least k distance apart. Return any valid arrangement or empty string if impossible.\n\n**Example:**\n```\nInput: s = "aabbcc", k = 3\nOutput: "abcabc"\n```', 'Hint 1: Greedy with priority queue.\n---\nHint 2: Pick most frequent character first.\n---\nHint 3: Use cooldown queue to enforce k distance.', '## Solution: Heap + Cooldown Queue\n\nUse max heap by frequency, cooldown queue to track when chars can be reused.\n\nTime: O(n log k), Space: O(k)', 'HARD', 'string,heap,greedy,hash-table'),

('ALGO', 'META', 'STRINGS', 'Longest Chunked Palindrome', '# Longest Chunked Palindrome\n\nSplit string into k substrings such that: substring1 = substringk, substring2 = substring(k-1), etc. Return maximum k.\n\n**Example:**\n```\nInput: "ghiabcdefhelloadamhelloabcdefghi"\nOutput: 7\nExplanation: (ghi)(abcdef)(hello)(adam)(hello)(abcdef)(ghi)\n```', 'Hint 1: Greedy from both ends.\n---\nHint 2: Match smallest chunks first.\n---\nHint 3: Recursively solve middle part.', '## Solution: Greedy Two Pointer\n\nFrom both ends, find smallest matching chunks, recursively solve middle.\n\nTime: O(n²), Space: O(n)', 'HARD', 'string,greedy,recursion'),

('ALGO', 'AMAZON', 'STRINGS', 'Minimum Deletions to Make Palindrome', '# Minimum Deletions to Make Palindrome\n\nFind minimum number of characters to delete to make string a palindrome.\n\n**Example:**\n```\nInput: "abcddcba"\nOutput: 0\n\nInput: "abcdef"\nOutput: 5 (delete all but one)\n```', 'Hint 1: Longest Palindromic Subsequence.\n---\nHint 2: Answer = n - LPS length.\n---\nHint 3: Use DP to find LPS.', '## Solution: DP (LPS)\n\nFind longest palindromic subsequence using DP, answer is n - LPS.\n\nTime: O(n²), Space: O(n²)', 'MEDIUM', 'string,dynamic-programming,palindrome'),

('ALGO', 'GOOGLE', 'STRINGS', 'Count Substrings with Equal 0s and 1s', '# Count Substrings with Equal 0s and 1s\n\nGiven binary string, count substrings with equal number of 0s and 1s.\n\n**Example:**\n```\nInput: "00110011"\nOutput: 6\nExplanation: "0011", "01", "1100", "10", "0011", "01"\n```', 'Hint 1: Treat 0 as -1, find subarrays with sum 0.\n---\nHint 2: Use prefix sum with hash map.\n---\nHint 3: Count occurrences of each prefix sum.', '## Solution: Prefix Sum + HashMap\n\nReplace 0→-1, count subarrays with sum 0 using prefix sum.\n\nTime: O(n), Space: O(n)', 'MEDIUM', 'string,hash-table,prefix-sum'),

('ALGO', 'META', 'STRINGS', 'Wildcard Pattern Matching', '# Wildcard Pattern Matching\n\nImplement wildcard matching: ? matches single char, * matches any sequence.\n\n**Example:**\n```\nInput: s = "adceb", p = "*a*b"\nOutput: true\n```', 'Hint 1: Dynamic programming.\n---\nHint 2: dp[i][j] = s[0..i] matches p[0..j]\n---\nHint 3: Handle * specially - can match 0 or more chars.', '## Solution: 2D DP\n\ndp[i][j]: first i chars of s match first j chars of pattern\n\nTime: O(m*n), Space: O(m*n)', 'HARD', 'string,dynamic-programming,recursion'),

('ALGO', 'AMAZON', 'STRINGS', 'Minimum Number of Flips for Alternating String', '# Minimum Number of Flips for Alternating String\n\nGiven binary string, find minimum flips to make it alternating (010101... or 101010...).\n\n**Example:**\n```\nInput: "0100"\nOutput: 1\nExplanation: Flip to "0101"\n```', 'Hint 1: Only two target patterns: starting with 0 or 1.\n---\nHint 2: Count mismatches for each pattern.\n---\nHint 3: Return minimum.', '## Solution: Count Mismatches\n\nCompare against both patterns, return minimum mismatches.\n\nTime: O(n), Space: O(1)', 'EASY', 'string,greedy');
