-- Mixed Patterns Arena - 15 Problems (Require 2+ Algorithm Patterns)

USE faang;

INSERT INTO problem (module_type, category, arena, title, description_markdown, hints_markdown, solution_explanation_markdown, difficulty, tags) VALUES

('ALGO', 'GOOGLE', 'MIXED_PATTERNS', 'Word Ladder with Minimum Cost', '# Word Ladder with Minimum Cost\n\nGiven a start word, end word, and dictionary of words, each word has a cost. Find the minimum cost transformation sequence from start to end, where each intermediate word must be in the dictionary and differ by exactly one letter.\n\n**Example:**\n```\nInput: \n  start = "hit"\n  end = "cog"\n  wordList = ["hot","dot","dog","lot","log","cog"]\n  costs = [1, 2, 3, 4, 5, 1]\nOutput: 9\nExplanation: "hit" → "hot"(1) → "dot"(2) → "dog"(3) → "cog"(1) = 7... wait recalculate\n```', 'Hint 1: This is not just BFS - costs matter.\n---\nHint 2: Use Dijkstra''s algorithm for weighted shortest path.\n---\nHint 3: Build a graph where edges connect words differing by one letter.', '## Solution: Graph + Dijkstra + String Comparison\n\n**Patterns Used:** Graph construction, Dijkstra''s algorithm, String manipulation\n\n1. Build graph: words are nodes, edge if one letter different\n2. Use Dijkstra with priority queue (min cost)\n3. Track minimum cost to reach each word\n\nTime: O(n² * m + n log n) where n=words, m=word length\nSpace: O(n²)', 'HARD', 'graph,dijkstra,heap,string,bfs'),

('ALGO', 'META', 'MIXED_PATTERNS', 'Maximum Points Collecting Path in Grid', '# Maximum Points Collecting Path in Grid\n\nYou''re in top-left of m×n grid with points. You can only move right or down. Some cells are blocked. Additionally, you can use a special jump ability ONCE to jump over blocked cells (jump up to 2 cells in any direction). Find maximum points you can collect.\n\n**Example:**\n```\ngrid = [\n  [1, 2, -1, 4],\n  [3, -1, 5, 6],\n  [7, 8, 9, 10]\n]\n(-1 = blocked)\nOutput: 40 (with jump)\n```', 'Hint 1: DP with state tracking.\n---\nHint 2: State includes: position + whether jump used.\n---\nHint 3: dp[i][j][used_jump] = max points at (i,j) with jump state.', '## Solution: Matrix DP + State Machine + Pathfinding\n\n**Patterns Used:** 2D DP, State tracking, Grid traversal\n\n3D DP: dp[i][j][0/1] where third dimension tracks if jump used\n- Without jump: only right/down moves\n- With jump: can jump once to reach distant cells\n\nTime: O(m * n * k) where k is jump distance\nSpace: O(m * n)', 'HARD', 'dynamic-programming,matrix,state-machine,grid'),

('ALGO', 'AMAZON', 'MIXED_PATTERNS', 'Recover Binary Search Tree From Traversals', '# Recover Binary Search Tree From Traversals\n\nGiven two traversals (inorder and postorder) of a BST where TWO nodes were accidentally swapped, recover the original BST.\n\n**Example:**\n```\nInorder: [1, 6, 3, 4, 5, 2]\nPostorder: [1, 5, 4, 6, 2, 3]\nOutput: Root of recovered BST\n```', 'Hint 1: First reconstruct the tree from traversals.\n---\nHint 2: Then find the two swapped nodes (BST property violation).\n---\nHint 3: Use Morris traversal or inorder to find violations.', '## Solution: Tree Construction + Inorder Traversal + Two Pointers\n\n**Patterns Used:** Tree reconstruction, BST property, Inorder traversal\n\n1. Reconstruct tree from inorder + postorder (recursion + hashmap)\n2. Inorder traverse to find two violations\n3. Swap the two nodes back\n\nTime: O(n)\nSpace: O(n)', 'HARD', 'tree,recursion,hash-table,inorder,bst'),

('ALGO', 'GOOGLE', 'MIXED_PATTERNS', 'Minimum Knight Moves with Obstacles', '# Minimum Knight Moves with Obstacles\n\nOn an infinite chessboard, a knight starts at (0,0) and wants to reach (x,y). Some cells have obstacles. Find minimum moves needed, or -1 if impossible.\n\n**Example:**\n```\nInput: x = 5, y = 5, obstacles = [(2,2), (3,3)]\nOutput: 4\n```', 'Hint 1: BFS for shortest path.\n---\nHint 2: But infinite board - need bidirectional BFS.\n---\nHint 3: Use set to track obstacles efficiently.', '## Solution: Bidirectional BFS + Hash Set + Grid Navigation\n\n**Patterns Used:** BFS, Bidirectional search, Set for obstacles\n\n1. BFS from both start and end\n2. Stop when they meet\n3. Use HashSet for O(1) obstacle lookup\n4. Handle infinite board by limiting search area\n\nTime: O(max(|x|, |y|)²)\nSpace: O(max(|x|, |y|)²)', 'HARD', 'graph,bfs,bidirectional-search,hash-set,grid'),

('ALGO', 'META', 'MIXED_PATTERNS', 'Substring Concatenation All Words', '# Substring Concatenation All Words\n\nGiven string s and array of words (all same length), find all starting indices where a concatenation of ALL words appears as a substring (in any order).\n\n**Example:**\n```\nInput: s = "barfoothefoobarman", words = ["foo","bar"]\nOutput: [0, 9]\nExplanation: "barfoo" and "foobar"\n```', 'Hint 1: Sliding window of fixed size.\n---\nHint 2: Use hash maps to track word frequencies.\n---\nHint 3: Window size = word_length * word_count.', '## Solution: Sliding Window + Two Hash Maps + String Parsing\n\n**Patterns Used:** Sliding window, Hash map frequency matching, String manipulation\n\n1. Window size = len(word) * count(words)\n2. Slide window, extract word chunks\n3. Compare chunk frequency with target\n\nTime: O(n * m) where n=string length, m=word length\nSpace: O(k) where k=unique words', 'HARD', 'sliding-window,hash-table,string,two-pointers'),

('ALGO', 'AMAZON', 'MIXED_PATTERNS', 'Path With Maximum Minimum Value', '# Path With Maximum Minimum Value\n\nGiven m×n grid of integers, find a path from top-left to bottom-right that MAXIMIZES the MINIMUM value along the path. You can move right or down.\n\n**Example:**\n```\ngrid = [\n  [5, 4, 5],\n  [1, 2, 6],\n  [7, 4, 6]\n]\nOutput: 4\nExplanation: Path 5→4→5→6→6 has min=4\n```', 'Hint 1: Not a simple DP - need to maximize minimum.\n---\nHint 2: Binary search on the answer + BFS/DFS.\n---\nHint 3: Or use modified Dijkstra with max heap.', '## Solution: Binary Search + DFS OR Modified Dijkstra\n\n**Patterns Used:** Binary search, DFS/BFS, Heap, Matrix traversal\n\nApproach 1: Binary search on answer, check if path exists with all values ≥ mid\nApproach 2: Dijkstra with max heap tracking max-min path\n\nTime: O(mn log(max_val)) or O(mn log(mn))\nSpace: O(mn)', 'HARD', 'binary-search,dfs,dijkstra,heap,matrix,grid'),

('ALGO', 'GOOGLE', 'MIXED_PATTERNS', 'Remove Invalid Parentheses Minimum Removals', '# Remove Invalid Parentheses Minimum Removals\n\nGiven string with parentheses and letters, remove minimum number of invalid parentheses to make valid. Return all possible results.\n\n**Example:**\n```\nInput: "()())()"\nOutput: ["(())()","()()()"]\n```', 'Hint 1: BFS level by level, removing one char at a time.\n---\nHint 2: Or backtracking with pruning.\n---\nHint 3: Track how many left/right parens to remove.', '## Solution: BFS + Set for Deduplication + String Validation\n\n**Patterns Used:** BFS level traversal, HashSet, String validation, Backtracking\n\n1. BFS: try removing each character\n2. Check validity at each level\n3. Use set to avoid duplicates\n4. Stop at first valid level (minimum removals)\n\nTime: O(2^n) worst case\nSpace: O(n * 2^n)', 'HARD', 'bfs,backtracking,string,set,pruning'),

('ALGO', 'META', 'MIXED_PATTERNS', 'Count Unique Islands with Rotation', '# Count Unique Islands with Rotation\n\nGiven 2D grid, count number of UNIQUE islands. Two islands are same if one can be rotated (90°, 180°, 270°) to match the other.\n\n**Example:**\n```\ngrid = [\n  [1,1,0,0],\n  [1,0,0,1],\n  [0,0,1,1]\n]\nOutput: 2 (some islands are rotations of each other)\n```', 'Hint 1: DFS/BFS to find each island.\n---\nHint 2: Normalize island shape using coordinates.\n---\nHint 3: Generate all 4 rotations and canonicalize.', '## Solution: DFS + Hash Set + Geometry Transformation\n\n**Patterns Used:** DFS, Coordinate normalization, Set for uniqueness, Matrix rotation\n\n1. DFS to extract each island\n2. Store relative coordinates\n3. Generate all 4 rotations\n4. Canonicalize (use min representation)\n5. Add to set\n\nTime: O(mn)\nSpace: O(mn)', 'HARD', 'dfs,matrix,hash-set,geometry,transformation'),

('ALGO', 'AMAZON', 'MIXED_PATTERNS', 'Longest Increasing Path in Matrix', '# Longest Increasing Path in Matrix\n\nGiven m×n matrix, find length of longest increasing path. You can move in 4 directions.\n\n**Example:**\n```\nmatrix = [\n  [9,9,4],\n  [6,6,8],\n  [2,1,1]\n]\nOutput: 4 (1→2→6→9)\n```', 'Hint 1: DFS with memoization.\n---\nHint 2: dp[i][j] = longest path starting at (i,j).\n---\nHint 3: Topological sort also works (treat as DAG).', '## Solution: DFS + Memoization OR Topological Sort\n\n**Patterns Used:** DFS, DP memoization, Matrix traversal, DAG\n\n1. DFS from each cell\n2. Memoize longest path from each position\n3. Only visit neighbors with larger values\n\nTime: O(mn)\nSpace: O(mn)', 'MEDIUM', 'dfs,dynamic-programming,memoization,matrix,dag'),

('ALGO', 'GOOGLE', 'MIXED_PATTERNS', 'Word Search II (Trie + Backtracking)', '# Word Search II\n\nGiven m×n board and list of words, find all words that can be formed by adjacent letters (no cell reuse in same word).\n\n**Example:**\n```\nboard = [\n  [''o'',''a'',''a'',''n''],\n  [''e'',''t'',''a'',''e''],\n  [''i'',''h'',''k'',''r''],\n  [''i'',''f'',''l'',''v'']\n]\nwords = ["oath","pea","eat","rain"]\nOutput: ["oath","eat"]\n```', 'Hint 1: Build a Trie from word list.\n---\nHint 2: DFS/Backtrack from each cell.\n---\nHint 3: Prune search using Trie prefixes.', '## Solution: Trie Construction + DFS Backtracking + Matrix Traversal\n\n**Patterns Used:** Trie, DFS, Backtracking, Matrix, Set for results\n\n1. Build Trie from words\n2. DFS from each cell with backtracking\n3. Use Trie to prune invalid paths\n4. Mark visited cells, unmark on backtrack\n\nTime: O(mn * 4^L) where L=max word length\nSpace: O(total characters in words)', 'HARD', 'trie,dfs,backtracking,matrix,string'),

('ALGO', 'META', 'MIXED_PATTERNS', 'Trapping Rain Water 2D', '# Trapping Rain Water 2D\n\nGiven m×n height map, compute how much water can be trapped after raining.\n\n**Example:**\n```\nheightMap = [\n  [1,4,3,1,3,2],\n  [3,2,1,3,2,4],\n  [2,3,3,2,3,1]\n]\nOutput: 4\n```', 'Hint 1: Water level determined by lowest boundary.\n---\nHint 2: Use min heap to process cells from outside in.\n---\nHint 3: Similar to Dijkstra - expand from lowest height.', '## Solution: Min Heap + BFS + Priority Queue\n\n**Patterns Used:** Heap, BFS, Matrix boundary processing\n\n1. Start from all boundary cells (min heap)\n2. Process lowest height cell\n3. Water level = max(current height, boundary height)\n4. Expand inward\n\nTime: O(mn log(mn))\nSpace: O(mn)', 'HARD', 'heap,bfs,matrix,priority-queue,greedy'),

('ALGO', 'AMAZON', 'MIXED_PATTERNS', 'Shortest Path Visiting All Nodes', '# Shortest Path Visiting All Nodes\n\nGiven undirected graph (n nodes), find shortest path that visits all nodes (can revisit). Can start from any node.\n\n**Example:**\n```\ngraph = [[1,2,3],[0],[0],[0]]\nOutput: 4\nExplanation: Start at 0, visit all in 4 steps\n```', 'Hint 1: BFS with state = (current_node, visited_set).\n---\nHint 2: Use bitmask to represent visited set.\n---\nHint 3: State: (node, mask) where mask tracks visited nodes.', '## Solution: BFS + Bitmask DP + Graph Traversal\n\n**Patterns Used:** BFS, Bitmask state compression, DP\n\n1. State: (node, visited_bitmask)\n2. BFS from all nodes simultaneously  \n3. Target: visited_bitmask == (1<<n)-1\n4. Track (node, mask) → distance\n\nTime: O(n² * 2^n)\nSpace: O(n * 2^n)', 'HARD', 'bfs,graph,bitmask,dynamic-programming,state-compression'),

('ALGO', 'GOOGLE', 'MIXED_PATTERNS', 'Minimum Cost to Merge Stones', '# Minimum Cost to Merge Stones\n\nGiven array of stone piles and k (you can merge k consecutive piles into 1 with cost = sum of stones), find minimum cost to merge into 1 pile. Return -1 if impossible.\n\n**Example:**\n```\nInput: stones = [3,2,4,1], k = 2\nOutput: 20\nExplanation: Merge strategy matters\n```', 'Hint 1: Interval DP.\n---\nHint 2: dp[i][j][m] = min cost to merge stones[i..j] into m piles.\n---\nHint 3: Check if (n-1) % (k-1) == 0 for validity.', '## Solution: Interval DP + Prefix Sum + Math\n\n**Patterns Used:** DP on intervals, Prefix sum for range queries, Mathematical validation\n\n3D DP: dp[i][j][m] = cost to merge i..j into m piles\nUse prefix sum for quick range sum calculation\n\nTime: O(n³ * k)\nSpace: O(n² * k)', 'HARD', 'dynamic-programming,interval-dp,prefix-sum,math'),

('ALGO', 'META', 'MIXED_PATTERNS', 'Clone Graph with Random Pointers', '# Clone Graph with Random Pointers\n\nGiven a graph where each node has:\n- List of neighbors\n- Random pointer to any node or null\n\nReturn a deep copy.\n\n**Example:**\n```\nNode structure:\nclass Node {\n  int val;\n  List<Node> neighbors;\n  Node random;\n}\n```', 'Hint 1: HashMap to map original → clone.\n---\nHint 2: First pass: create all nodes.\n---\nHint 3: Second pass: connect neighbors and random pointers.', '## Solution: Graph DFS + HashMap + Two-Pass Clone\n\n**Patterns Used:** DFS/BFS, HashMap for mapping, Graph traversal\n\n1. Create all nodes, map original→clone\n2. DFS/BFS to traverse graph\n3. Copy neighbors and random pointers using map\n\nTime: O(n + e) where e=edges\nSpace: O(n)', 'MEDIUM', 'graph,dfs,hash-table,clone,two-pass'),

('ALGO', 'AMAZON', 'MIXED_PATTERNS', 'Course Schedule with Prerequisites and Corequisites', '# Course Schedule with Prerequisites and Corequisites\n\nGiven n courses with:\n- Prerequisites: must take before this course\n- Corequisites: must take in same semester\n\nFind minimum semesters needed to complete all courses, or -1 if impossible.\n\n**Example:**\n```\nInput: n=4, \n  prerequisites=[[1,0],[2,0],[3,1],[3,2]],\n  corequisites=[[1,2]]\nOutput: 3 semesters\n```', 'Hint 1: Topological sort for prerequisites.\n---\nHint 2: Union-Find for corequisites (group them).\n---\nHint 3: Apply topological sort on groups.', '## Solution: Topological Sort + Union-Find + Graph DAG\n\n**Patterns Used:** Kahn''s algorithm, Union-Find, Graph with constraints\n\n1. Union-Find to group corequisite courses\n2. Build DAG between groups\n3. Topological sort with BFS (track levels)\n4. Check for cycles\n\nTime: O(n + e)\nSpace: O(n)', 'HARD', 'graph,topological-sort,union-find,bfs,dag');
